import { decryptNews } from "./crypto.mjs?v=20260930-share1";

const $ = (selector) => document.querySelector(selector);
const state = { data: null, view: "recommended", category: "", query: "", limit: 60, saved: {}, read: {} };
const storageKey = "herajika-news:reading:v1";
let loadGeneration = 0;
const date = (value) => value ? new Intl.DateTimeFormat("ja-JP", { timeZone: "Asia/Tokyo", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "未更新";
const node = (tag, cls, text) => { const element = document.createElement(tag); if (cls) element.className = cls; if (text !== undefined) element.textContent = text; return element; };
function toast(message) { $("#toast").textContent = message; $("#toast").hidden = false; clearTimeout(toast.timer); toast.timer = setTimeout(() => $("#toast").hidden = true, 3500); }
try { const stored = JSON.parse(localStorage.getItem(storageKey) || "{}"); if (stored.saved && typeof stored.saved === "object") state.saved = stored.saved; if (stored.read && typeof stored.read === "object") state.read = stored.read; } catch {}
function persist() { try { localStorage.setItem(storageKey, JSON.stringify({ saved: state.saved, read: state.read })); return true; } catch { toast("このブラウザでは保存できません。ページを閉じると保存状態が消えます。"); return false; } }
function sourceLink(url, label = "元記事を読む ↗") { try { const parsed = new URL(url); if (!["https:", "http:"].includes(parsed.protocol) || parsed.username || parsed.password) throw new Error(); const link = node("a", "source-link", label); link.href = parsed.href; link.target = "_blank"; link.rel = "noopener noreferrer"; link.referrerPolicy = "no-referrer"; return link; } catch { return node("span", "muted", "元記事のURLを確認できません。"); } }
const basis = (article) => article.summary ? "AI要約 · " + (article.basis === "feed_content" ? "RSS本文に基づく" : "配信元の紹介文に基づく") : "配信元の紹介文 · AI要約なし";
const articleDate = (article) => (article.date_basis === "published" ? "" : "取得 ") + date(article.published);
function saveButton(article) { const saved = !!state.saved[article.url]; const button = node("button", "save-button" + (saved ? " saved" : ""), saved ? "◆" : "◇"); button.setAttribute("aria-label", saved ? "保存を解除" : "あとで読むに保存"); button.setAttribute("aria-pressed", String(saved)); button.addEventListener("click", () => { if (state.saved[article.url]) delete state.saved[article.url]; else state.saved[article.url] = true; const ok = persist(); const nowSaved = !!state.saved[article.url]; button.textContent = nowSaved ? "◆" : "◇"; button.classList.toggle("saved", nowSaved); button.setAttribute("aria-pressed", String(nowSaved)); button.setAttribute("aria-label", nowSaved ? "保存を解除" : "あとで読むに保存"); render(); if (ok) toast(nowSaved ? "このブラウザのあとで読むに保存しました。" : "保存を解除しました。"); }); return button; }
function card(article, index) { const element = node("article", "article-card" + (index < 3 && state.view === "recommended" ? " featured" : "")); const top = node("div", "card-top"); top.append(node("span", "topic-tag", article.matches[0]?.name || article.category), saveButton(article)); element.append(top, node("div", "source-line", article.source + " · " + articleDate(article))); const heading = node("h3"); const title = node("button", "title-button", article.title); title.addEventListener("click", () => openDetail(article)); heading.append(title); element.append(heading, node("p", "summary", article.summary || article.excerpt || "詳細は元記事をご覧ください。"), node("div", "basis", basis(article))); const reason = node("div", "reason"); reason.append(node("span", "reason-label", "WHY FOR YOU"), node("span", "", article.reason)); element.append(reason); const bottom = node("div", "card-bottom"); const more = node("button", "", "要点を見る ↗"); more.addEventListener("click", () => openDetail(article)); bottom.append(more, sourceLink(article.url)); if (state.read[article.url]) bottom.append(node("span", "read-badge", "既読")); element.append(bottom); return element; }
function selectItems() { return state.data.items.filter((article) => (state.view === "new" || !article.duplicate_of || state.saved[article.url]) && (state.view !== "saved" || state.saved[article.url]) && (!state.category || article.category === state.category || article.matches.some((match) => match.name === state.category)) && (!state.query || (article.title + " " + (article.summary || "") + " " + article.excerpt + " " + article.source).toLocaleLowerCase("ja").includes(state.query.toLocaleLowerCase("ja")))).sort(state.view === "new" ? (a, b) => b.published.localeCompare(a.published) : (a, b) => b.priority - a.priority || b.published.localeCompare(a.published)); }
function render() { if (!state.data) return; const selected = selectItems(), visible = selected.slice(0, state.limit), grid = $("#article-grid"); grid.replaceChildren(...visible.map(card)); if (!visible.length) grid.append(node("div", "empty", state.view === "saved" ? "◇を押した記事を、このブラウザに保存できます。" : "この条件の記事はありません。")); $("#result-count").textContent = `${visible.length} / ${selected.length} 件`; $("#load-more").hidden = visible.length >= selected.length; $("#feed-title").textContent = state.category || ({ recommended: "あなたへのおすすめ", new: "すべての新着", saved: "あとで読む" }[state.view]); $("#feed-eyebrow").textContent = state.view === "new" ? "LATEST STORIES" : state.view === "saved" ? "YOUR READING LIST" : "CURATED FOR YOU"; $("#saved-count").textContent = state.data.items.filter((article) => state.saved[article.url]).length; document.querySelectorAll("[data-view]").forEach((button) => button.classList.toggle("active", button.dataset.view === state.view && !state.category)); document.querySelectorAll("[data-category]").forEach((button) => button.classList.toggle("active", button.dataset.category === state.category)); }
function category(value) { state.category = value; if (value) state.view = "recommended"; state.limit = 60; render(); }
function categories() { const nav = $("#interests-nav"), chips = $("#category-chips"); nav.replaceChildren(); chips.replaceChildren(); const all = node("button", "chip", "すべて"); all.dataset.category = ""; all.addEventListener("click", () => category("")); chips.append(all); for (const value of state.data.categories) { const button = node("button", "nav interest-nav"); button.dataset.category = value; button.append(node("span", "interest-dot"), node("span", "", value)); button.addEventListener("click", () => category(value)); nav.append(button); const chip = node("button", "chip", value); chip.dataset.category = value; chip.addEventListener("click", () => category(value)); chips.append(chip); } }
function openDetail(article) { const root = $("#detail-content"), top = node("div", "dialog-top"); const close = node("button", "icon-button", "×"); close.setAttribute("aria-label", "記事を閉じる"); close.addEventListener("click", () => $("#detail-dialog").close()); top.append(node("span", "eyebrow", article.source), close); root.replaceChildren(top, node("h2", "detail-title", article.title), node("div", "source-line", articleDate(article)), node("p", "detail-summary", article.summary || article.excerpt)); if (article.points.length) { root.append(node("h3", "", "要点")); const points = node("ul", "detail-points"); points.append(...article.points.map((point) => node("li", "", point))); root.append(points); } root.append(node("p", "fine-print", basis(article)), node("div", "detail-reason", article.reason)); const actions = node("div", "dialog-top"), link = sourceLink(article.url, "元記事で詳しく読む ↗"); link.className = "detail-source"; actions.append(link, saveButton(article)); root.append(actions); if (article.summary && article.excerpt) { const details = node("details", "detail-excerpt"); details.append(node("summary", "", "要約の根拠になった配信文を見る"), node("p", "", article.excerpt)); root.append(details); } $("#detail-dialog").showModal(); state.read[article.url] = true; persist(); render(); }
function lock(message) { state.data = null; $("#reader").hidden = true; $("#locked").hidden = false; $("#lock-message").textContent = message; $("#detail-dialog").close(); $("#detail-content").replaceChildren(); $("#article-grid").replaceChildren(); }
async function load() { const generation = ++loadGeneration; const key = new URLSearchParams(location.hash.slice(1)).get("key"); if (!key || !/^[A-Za-z0-9_-]{43}$/.test(key)) { lock("鍵付きリンクから開くと、ニュースを読めます。"); $("#unlock-retry").hidden = true; return; } const button = $("#refresh-button"); button.disabled = true; try { if (!crypto.subtle) throw new Error(); const response = await fetch("news.enc.json?t=" + Date.now(), { cache: "no-store", referrerPolicy: "no-referrer" }); if (!response.ok) throw new Error(); const data = await decryptNews(await response.json(), key); if (generation !== loadGeneration) return; state.data = data; categories(); $("#article-count").textContent = data.items.length; $("#summary-count").textContent = data.items.filter((article) => article.summary).length; $("#update-status").textContent = "更新 " + date(data.updated_at || data.exported_at); $("#schedule-note").textContent = data.schedule ? `毎朝7:45に更新開始、8:30までの公開を目標にしています。最終更新日時を確認してお読みください。最新${data.items.length}件を掲載。` : `PC版が起動している間、${data.refresh_hours}時間ごとに収集してWebへ送信。最新${data.items.length}件を掲載。`; $("#notice").hidden = true; $("#locked").hidden = true; $("#reader").hidden = false; $("#unlock-retry").hidden = true; render(); } catch { if (generation !== loadGeneration) return; if (state.data) { $("#notice").hidden = false; $("#notice").textContent = "新しい版を読み込めませんでした。表示中の記事は引き続き読めます。"; } else { lock("ニュースを開けませんでした。鍵付きリンクの末尾と接続を確認してください。"); $("#unlock-retry").hidden = false; } } finally { if (generation === loadGeneration) button.disabled = false; } }
document.querySelectorAll("[data-view]").forEach((button) => button.addEventListener("click", () => { state.view = button.dataset.view; state.category = ""; state.limit = 60; render(); }));
$("#home").addEventListener("click", (event) => { event.preventDefault(); state.view = "recommended"; category(""); });
$("#search").addEventListener("input", () => { state.query = $("#search").value.trim(); state.limit = 60; render(); });
$("#load-more").addEventListener("click", () => { state.limit += 60; render(); });
$("#refresh-button").addEventListener("click", load); $("#unlock-retry").addEventListener("click", load);
window.addEventListener("hashchange", () => { lock("ニュースを開いています…"); load(); });
document.addEventListener("keydown", (event) => { if (event.key === "/" && !["INPUT", "TEXTAREA"].includes(document.activeElement.tagName) && state.data) { event.preventDefault(); $("#search").focus(); } });
$("#today").textContent = new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Tokyo", day: "2-digit", month: "long", year: "numeric" }).format(new Date()).toUpperCase();
load();
